export const products = [
  {
    id: 1,
    name: "Almond Brown Sugar Croissant",
    desc: "Sweet croissant topped with toasted almonds",
    price: 12.98,
    image: "/assets/p1.jpg",
    category: "croissant",
  },
  {
    id: 2,
    name: "Butter Chocolate Croissant",
    desc: "Flaky croissant with melted chocolate",
    price: 11.5,
    image: "/assets/BUTTER-CROISSANT-CHOCOLATE.jpg",
    category: "croissant",
  },
  {
    id: 3,
    name: "Smoke Tenderloin Croissant",
    desc: "Tenderloin beef with fresh vegetables",
    price: 10.01,
    image: "/assets/p2.webp",
    category: "croissant",
  },
  {
    id: 4,
    name: "Classic Belgian Waffle",
    desc: "Crispy waffle with maple syrup",
    price: 8.75,
    image: "/assets/Classic Belgian Waffle.webp",
    category: "waffle",
  },
  {
    id: 5,
    name: "Strawberry Cream Waffle",
    desc: "Waffle topped with strawberries and cream",
    price: 9.4,
    image: "/assets/Strawberry Cream Waffle.webp",
    category: "waffle",
  },
  {
    id: 6,
    name: "Caramel Latte",
    desc: "Smooth espresso with caramel milk",
    price: 6.2,
    image: "/assets/Caramel Latte.jpg",
    category: "coffee",
  },
  {
    id: 7,
    name: "Vanilla Cappuccino",
    desc: "Rich cappuccino with vanilla aroma",
    price: 5.8,
    image: "/assets/Vanilla Cappuccino.webp",
    category: "coffee",
  },
  {
    id: 8,
    name: "Classic Espresso",
    desc: "Strong and bold espresso shot",
    price: 4.5,
    image: "/assets/Classic Espresso.jpg",
    category: "coffee",
  },
  {
    id: 9,
    name: "Chocolate Ice Cream",
    desc: "Creamy chocolate ice cream scoop",
    price: 7.1,
    image: "/assets/Chocolate Ice Cream.jpg",
    category: "ice-cream",
  },
  {
    id: 10,
    name: "Vanilla Berry Ice Cream",
    desc: "Vanilla ice cream with berry topping",
    price: 7.6,
    image: "/assets/Vanilla Berry Ice Cream.jpeg",
    category: "ice-cream",
  },
];
