export const recipes = [
  {
    id: "spicy-ramen",
    title: "Spicy Ramen Noodle",
    calories: "239 kcal",
    time: "15 mins",
    rating: 4.7,
    recook: "4.5M",
    image: "/assets/spccy.webp",
    ingredients: ["Noodle", "Chicken", "Vegetable", "Onion", "Shrimp"],
    description:
      "A warm and spicy ramen dish with rich broth, tender chicken, shrimp, and fresh vegetables.",
    link: "google.com",
  },
  {
    id: "cheese-sandwich",
    title: "Cheese Sandwich",
    calories: "210 kcal",
    time: "10 mins",
    rating: 4.5,
    recook: "2.1M",
    image: "/assets/cheese.jpg",
    ingredients: ["Bread", "Cheese", "Butter"],
    description: "A crispy grilled sandwich with melted cheese inside.",
    link: "google.com",
  },
  {
    id: "chocolate-icecream",
    title: "Chocolate Ice Cream",
    calories: "180 kcal",
    time: "5 mins",
    rating: 4.8,
    recook: "3.2M",
    image: "/assets/Tasty-Chocolate-Ice-Cream.jpg",
    ingredients: ["Milk", "Cocoa", "Sugar"],
    description: "Creamy homemade chocolate ice cream.",
    link: "google.com",
  },
];
